name: Update Waydroid Images

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'update_waydroid_latest.py'
      - '.github/workflows/update-images.yml'
      - 'waydroid-image.spec.template' # Trigger if template changes

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Rename spec to template
      run: |
        if [ -f "waydroid-image.spec" ] && [ ! -f "waydroid-image.spec.template" ]; then
          echo "Moving waydroid-image.spec to waydroid-image.spec.template"
          mv waydroid-image.spec waydroid-image.spec.template
        else
          echo "Template file already exists or spec file not found."
        fi
        
    - name: Run update script
      run: |
        python3 update_waydroid_latest.py
    
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add waydroid-image.spec waydroid-urls.json
        git commit -m "Automated: Update Waydroid image URLs and version

        Auto-update by GitHub Actions
        Date: $(date -u +'%Y-%m-%d %H:%M UTC')"
        git pull --rebase
        git push
